### ISSUE TITLE
Make sure that both bundles are in the same app group

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2324] opened 2023-10-12 21:56 UTC
This is the message I see for logging in for the first time:

![Screenshot 2023-10-12 at 15 14 12](https://github.com/firezone/firezone/assets/167144/e41147ca-ff90-4bad-bca3-39180fb9d077)

Probably a result of recent CI changes to self-sign applications.

**Comment by jamilbk** [comment] 2023-10-14 00:42
@roop Perhaps this would be a good candidate for our first unit test. Could run on a `macos-12` runner.

**Comment by jamilbk** [comment] 2023-10-15 21:14
@AndrewDryga Unfortunately it won't be possible for us to test on `macos-12` without access to a live machine. I managed to setup a local macos-12 vm, but [VMs aren't eligible for Apple ID signins](https://developer.apple.com/forums/thread/707682), and therefore Test Flight installs:

<img width="1182" alt="Screenshot 2023-10-15 at 2 06 27 PM" src="https://github.com/firezone/firezone/assets/167144/a5da57cb-3b33-4333-a828-1373421b3de8">

You might have to be our macOS 12 guinea pig for the time being :-).

After #2333 is merged, could you do the following test to see if this is still an issue?

1. Drag Firezone.app to trash and empty
2. Remove group container folder: `sudo rm -rf ~/Library/Group\ Containers/47R2M6779T.group.dev.firezone.firezone`
3. Create a new user account on your Mac
4. Log in, set up Test Flight in this new user account
5. Install the latest Firezone beta and perform the same test

**Comment by jamilbk** [comment] 2023-10-17 14:04
@bmanifold has confirmed it's not an issue for macOS-13. Seems to be an issue for Andrew / macOS-12 only, deprioritizing for now.

**Comment by roop** [comment] 2023-10-17 17:55
@AndrewDryga To start with a clean slate, please also do these:

 1. Open System Settings > VPN, and remove any VPNs with name starting as "Firezone" (click on the (i) to see the "Remove configuration" button)
 2. Open Keychain Access, and remove any keychain items named "Firezone Access Token"

**Comment by jamilbk** [comment] 2023-12-05 22:24
@roop We managed to reproduce this reliably.

This console.app log message occurs when the app starts and checks for the token:

```
error:[-34018] Error Domain=NSOSStatusErrorDomain Code=-34018 "Client has neither com.apple.application-identifier nor com.apple.security.application-groups nor keychain-access-groups entitlements" UserInfo={numberOfErrorsDeep=0, NSDescription=Client has neither com.apple.application-identifier nor com.apple.security.application-groups nor keychain-access-groups entitlements}
```

It looks like maybe macOS 12 needs another entitlement defined?

**Comment by jamilbk** [comment] 2023-12-26 02:41
macos-12 support not planned in the near future.

**Comment by jamilbk** [comment] 2024-04-08 14:30
Fixed with the keychain-tunnel refactor

**Closed as completed by jamilbk** 2024-04-08 14:30 UTC
Labels: kind/bug, kind/wontfix, area/apple_client, business_value/low
