### ISSUE TITLE
ux(portal): Policy page doesn't say which page I'm on

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5696] opened 2024-07-03 16:51 UTC
#### Describe the bug

It says "showing 10 of 114" but doesn't say which 10.

I guess this is an effect of cursor-based pagination but it's confusing to see

#### To Reproduce

- Go to https://app.firez.one/firezone/policies
- Click around

#### Expected behavior

Expected something like Page 1, Page 2, etc.

#### Screenshots / Logs

<img width="1147" alt="image" src="https://github.com/firezone/firezone/assets/13400041/5cc7efa5-25cf-4f35-84ce-67d5db13355d">

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Admin portal
- _Firezone Version (e.g. 1.0.0 or N/A):_ N/A
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ N/A
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Staging network

#### Additional context

N/A

**Comment by AndrewDryga** [comment] 2024-07-03 18:28
Yeah, with cursors there is no way tell on which page you are. The tradeoff is following:
- offset paging is slow because DB will actually load all results up to a page you at and only then return subset of it (bad when you go to page 100 for example; it's a common DDoS vector); it's not stable for things that rapidly change (if page size is 10 and 10 items are inserted between every time you click next page you will always see the same results); it does allow to know the page number.
- cursor paging is fast, stable but doesn't let to know where you are at now and quickly jump between pages.

We can implement offset paging for some of the pages, but for things like REST API and activity logs (large tables) we must keep using cursor one.

**Comment by AndrewDryga** [comment] 2024-08-29 19:44
Closing as dupe of #5732

**Closed as completed by AndrewDryga** 2024-08-29 19:44 UTC
Labels: area/portal, needs triage
