### ISSUE TITLE
Windows 1.3.10 fails to establish connections to CIDR and DNS resources

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#7254] opened 2024-11-04 16:53 UTC
Looks like the connection intents never make it through? Possibly related to new control protocol or TCP DNS.

[connlib.2024-11-04-16-43-10.zip](https://github.com/user-attachments/files/17621375/connlib.2024-11-04-16-43-10.zip)

**Comment by thomaseizinger** [comment] 2024-11-04 19:41
Likely duplicate of #7200.

**Comment by jamilbk** [comment] 2024-11-04 20:04
Hmm I'm not so sure. This issue is preventing connections to CIDR and DNS resources. Connection to the portal is fine. The Internet Resource works fine for me.

It seems that the connection intents never make it to the Gateway(s)?

**Comment by thomaseizinger** [comment] 2024-11-05 03:29
> Connection to the portal is fine.

Only in the beginning, later down the line we see "Connecting to portal" and then nothing there after. This is also what we have been seeing in #7200.

**Comment by thomaseizinger** [comment] 2024-11-05 04:06
Doesn't reproduce on my VM :(

**Comment by thomaseizinger** [comment] 2024-11-07 00:53
I don't think this is fixed, I just ran into this on my Windows VM.

**Comment by thomaseizinger** [comment] 2024-11-07 00:59
[firezone_logs_2024_11_07-00-39.zip](https://github.com/user-attachments/files/17654633/firezone_logs_2024_11_07-00-39.zip)

**Closed as completed** 2024-11-08 12:33 UTC
Labels: kind/bug, area/connlib, area/windows_client
