### ISSUE TITLE
Better determine whether to use IPv4 or IPv6 for DNS Resources

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#7381] opened 2024-11-19 21:00 UTC
For environments where `A` and `AAAA` records exist for a DNS Resource, it could be possible that the Gateway isn't intelligent enough to know which IP to connect to correspondingly. For example on AWS, hosts by default have both records active, but IPv6 isn't routable by default in many VPCs.

Unfortunately there's not a straightforward way to propagate the IP stack connectivity from Gateway to Client, but perhaps ICMP can be used to signal back to the application on which stack ultimately to use to connect to the Resource.

**Comment by thomaseizinger** [comment] 2024-11-19 21:03
Yeah we can't currently NAT ICMPs back: https://github.com/firezone/firezone/issues/5614.

**Comment by thomaseizinger** [comment] 2024-11-27 23:09
Dupe of #5614.

**Closed as not planned by thomaseizinger** 2024-11-27 23:09 UTC
Labels: kind/bug, area/gateway, kind/UX/user
