### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by Arvi89** [CloudFire-LLC/cloudfire#1491] opened 2023-03-08 10:31 UTC
**Is your feature request related to a problem? Please describe.**
Hello!
I've tried firezone and it's awesome, but I was thinking it would be really nice to have groups for users. Then you can create rules for a group instead of a single user, also set different configuration for different groups (dev and sales might have different needs for the VPN for example, and I might not want to edit manually each created device).

**Describe the solution you'd like**
We would need a "Group" page to manage groups, and see which users are in. When checking a user, we could also change the groupe there. If multiple groups is allowed, groups need to have an order of significance, to select which config will be selected by default (could be overrided) 

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by jamilbk** [comment] 2023-03-08 15:16
Thanks for the suggestion! These are coming in some form, but not ETA on that yet. Going to close as a dupe of #830

**Closed as not planned by jamilbk** 2023-03-08 15:16 UTC
Labels: kind/feature
