### ISSUE TITLE
GET /v0/users (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for

### ISSUE THREAD

**Issue by defp** [CloudFire-LLC/cloudfire#1715] opened 2023-06-29 10:39 UTC
**Screenshots / Logs**
 ```
request_id=F20a7t0QPJs11wQAAALE [info] GET /v0/users
firezone-firezone-1  | 10:37:28.547 erl_level=error domain=cowboy pid=<0.934.0> [error] #PID<0.935.0> running FzHttpWeb.Endpoint (connection #PID<0.934.0>, stream id 1) terminated
 firezone-firezone-1  | Request: GET /v0/users
firezone-firezone-1  | ** (exit) an exception was raised:
firezone-firezone-1  |     ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Protocol.UndefinedError{protocol: String.Chars, value: %CaseClauseError{term: "9"}, description: ""} of type Protocol.UndefinedError (a struct). This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, FzHttp.Types.IPPort, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Postgrex.INET, Time, Tuple, URI
firezone-firezone-1  |         (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
firezone-firezone-1  |         (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/controller.ex:1010: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
firezone-firezone-1  |         (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/controller.ex:976: Phoenix.Controller.render_and_send/4
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:84: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
firezone-firezone-1  |         (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2~
```
**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12]
 - OS: [e.g. Linux]
 - Distro: [e.g. Ubuntu 18.04]
 - Kernel version: [e.g. 5.10.11]
 - Deployment method: [e.g. Docker / Omnibus / Source]

**Additional context**

**Comment by defp** [comment] 2023-06-29 10:40
When the token of fz is not available it will cause the

**Comment by jamilbk** [comment] 2023-06-29 13:11
Dupe of https://github.com/firezone/firezone/issues/1707

**Closed as completed by jamilbk** 2023-06-29 13:11 UTC
Labels: kind/bug
