### ISSUE TITLE
VPN Handshake fails randomly

### ISSUE THREAD

**Issue by kutsav** [CloudFire-LLC/cloudfire#1596] opened 2023-05-06 17:37 UTC
**Describe the bug**
When connecting to VPN via Wireguard on Mac, handshake fails sometimes and have to disconnect and connect again to succesfully establish the handshake, this retry step can go up to 3-4 times as well sometimes. This causes a poor experience

**To Reproduce**
Just use docker based installation of 0.7.27 version

**Expected behavior**
The handshake should be seamless. For an org wide usage of VPN, VPN connection should be established in one go

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version 0.7.27
 - OS: MacOS [Client], Ubuntu 20[Firezone server]
 - Distro: Ubuntu 120
 - Deployment method: Docker
[This happens ob both docker and omnibus setup btw]

Sample screenshot of failed handshake scenario, never recovers from this state:
<img width="604" alt="Screenshot 2023-05-06 at 11 01 14 PM" src="https://user-images.githubusercontent.com/22631337/236638808-5354a162-19dd-40cb-90dd-700c75a8abe8.png">

Whereas after disconnecting and then trying connecting(this can range from 1-3 times), able to see the handshake being established:
<img width="301" alt="Screenshot 2023-05-06 at 11 06 11 PM" src="https://user-images.githubusercontent.com/22631337/236638874-1a191d92-ca4b-4a45-a013-b6d311199437.png">

**Comment by jamilbk** [comment] 2023-05-06 17:38
Does this happen for all clients? Is your network blocking WireGuard?

**Comment by jamilbk** [comment] 2023-05-06 17:39
This doesn't *feel* like a Firezone issue, but try upgrading to 0.7.28 as we fixed a bug related to the peer keys on the WireGuard interface. Don't think it would be causing this behavior though.

**Comment by kutsav** [comment] 2023-05-06 17:41
no blocking from network side, as reconnecting fixes the problem. Also, tested this from multiple networks.

Will upgrade to 0.7.28 and test once as well

**Comment by kutsav** [comment] 2023-05-06 17:45
just now updated the docker image and tested, same behaviour persists on MacOS

**Comment by jamilbk** [comment] 2023-05-06 18:37
Do you have your Firezone instance deployed behind a L4 Load Balancer such as AWS NLB?

**Comment by kutsav** [comment] 2023-05-06 18:39
no, its direct ec2 via public ip

**Comment by jamilbk** [comment] 2023-05-06 18:45
Does this only happen on the macOS client? Have you verified that clients for other OSes are working fine? Does it happen on multiple devices?

**Comment by jamilbk** [comment] 2023-05-06 18:46
You may want to make sure both client and server MTU are 1280 to eliminate the possibility fragmentation issues.

**Comment by kutsav** [comment] 2023-05-06 18:47
We mostly use macos so complaints there only. 
I tried setting up on iphone just now with doing disconnect and connect multiple times, and saw the same behaviour.

**Comment by jamilbk** [comment] 2023-05-06 18:49
Can you test connecting to a non-Firezone WG server in the same VPC? We use kernel WireGuard and the official WireGuard clients and just operate at a layer above. So we don't really have any impact on the tunnel itself

**Comment by kutsav** [comment] 2023-05-06 18:55
opened firewall on few public servers in same vpc and tested, no problem in connecting to those.

also checked mtu on my mac was 1500, but after setting it to 1280 tried multiple connect and disconnect, and same behaviour in those retries

**Comment by jamilbk** [comment] 2023-05-06 19:59
Looks like there may be some issue with the packets making it to that server. I’m unable to reproduce, so closing.

we’ve seen this happen with AWS NLB — I would double and triple check there’s nothing in the way.

perhaps try on a new server?

**Closed as not planned by jamilbk** 2023-05-06 19:59 UTC
Labels: kind/bug
