### ISSUE TITLE
Gateway reappears after being deleted when a new Gateway is deployed in the same site

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5275] opened 2024-06-07 04:42 UTC
1. Deploy a Gateway
2. Delete it
3. Notice it's not online anymore
4. Deploy a new Gateway
5. Notice you now have two Gateways online

**Comment by AndrewDryga** [comment] 2024-06-09 18:50
Dupe of https://github.com/firezone/firezone/issues/3257

**Closed as completed by AndrewDryga** 2024-06-09 18:50 UTC
Labels: kind/bug, area/portal, business_value/medium
