### ISSUE TITLE
Connection Expiry Notification for End Users

### ISSUE THREAD

**Issue by LegandaryRa** [CloudFire-LLC/cloudfire#1751] opened 2023-07-10 15:15 UTC
**Is your feature request related to a problem? Please describe.**
No Problem but a necessary feature which probably is a ton of work.
Create a way for users to immediately see if their VPN Connection is expired and have a link for authentication.

**Describe the solution you'd like**
Create a Firezone App/Client for each major Operating System. (Android, Linux, MacOS, Windows)

**Describe alternatives you've considered**
Maybe just an official script will do that pings a resource in the Network you are trying to connect to, preferably an endpoint in the Firezone deployment.  (if the Wireguard Tunnel is active). And open a Browser Window to the authentication portal.
This could be easily set up on a client Machine.

**Additional context**
Currently the feature to terminate the connection is not deploy-able as non tech-savvy users won't be able to figure out the problem on their own and re authenticate.

BR
LegandaryRa

**Comment by jamilbk** [comment] 2023-07-10 15:51
Closing as a dupe of #1329 

they’re coming

**Closed as not planned by jamilbk** 2023-07-10 15:51 UTC
Labels: kind/feature
