### ISSUE TITLE
Unable to create client; integer out of range

### ISSUE THREAD

**Issue by gbe0** [CloudFire-LLC/cloudfire#1340] opened 2023-01-19 07:07 UTC
Hi,

On 0.7.2 and 0.7.3 I am unable to create new clients, the following error shows in the logs:

```
2023-01-19_06:58:57.69871 14:58:57.682 [error] GenServer #PID<0.566.0> terminating
2023-01-19_06:58:57.69874 ** (DBConnection.EncodeError) Postgrex expected an integer in -9223372036854775808..9223372036854775807, got 17047240080733886429. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
2023-01-19_06:58:57.69875     (postgrex 0.16.5) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.encode_params/3
2023-01-19_06:58:57.69875     (postgrex 0.16.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
2023-01-19_06:58:57.69875     (db_connection 2.4.3) lib/db_connection.ex:1304: DBConnection.encode/5
2023-01-19_06:58:57.69875     (db_connection 2.4.3) lib/db_connection.ex:1404: DBConnection.run_prepare_execute/5
2023-01-19_06:58:57.69876     (db_connection 2.4.3) lib/db_connection.ex:644: DBConnection.parsed_prepare_execute/5
2023-01-19_06:58:57.69876     (db_connection 2.4.3) lib/db_connection.ex:636: DBConnection.prepare_execute/4
2023-01-19_06:58:57.69876     (ecto_sql 3.9.2) lib/ecto/adapters/postgres/connection.ex:70: Ecto.Adapters.Postgres.Connection.prepare_execute/5
2023-01-19_06:58:57.69876     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:836: Ecto.Adapters.SQL.execute!/5
2023-01-19_06:58:57.69877 Last message: %Phoenix.Socket.Message{topic: "lv:phx-FzujjS4ub8Xw7wRR", event: "event", payload: %{"cid" => 4, "event" => "save", "type" => "form", "value" => "device%5Bpublic_key%5D=gNR5R5QXRK5ipvDq%2FxaCHlY9wZcvWmsvvO4Bb7YinAo%3D&device%5Bpreshared_key%5D=&device%5Bname%5D=enlightened808F&device%5Bdescription%5D=&device%5Buse_default_allowed_ips%5D=true&device%5Buse_default_dns%5D=true&device%5Buse_default_endpoint%5D=true&device%5Buse_default_mtu%5D=true&device%5Buse_default_persistent_keepalive%5D=true&device%5Bipv4%5D=&device%5Bipv6%5D="}, ref: "36", join_ref: "34"}
```

I am guessing a previous database migration wasn't executed successfully but looking through the migrations I don't see anything that stands out.

**Comment by jamilbk** [comment] 2023-01-19 16:23
Thanks for the detailed report @gbe0. Unfortunately the crash is occurring in the Postgres adapter and so backtrace doesn't contain the application context. A couple clarifying questions to help pinpoint:

- ~~Are you creating via the REST API or the new device form?~~ Nevermind, looks to be from the form
- Version of Postgres you're running?

**Comment by jamilbk** [comment] 2023-01-19 16:33
cc @AndrewDryga -- possible bug with IP allocation.

**Comment by AndrewDryga** [comment] 2023-01-19 16:38
@gbe0 can you please share your IP configs? `WIREGUARD_*_NETWORK` and `WIREGUARD_*_ADDRESS`, is IPv6 enabled and how many devices do you have already?

**Comment by gbe0** [comment] 2023-01-19 17:58
Hi,

> ~~Are you creating via the REST API or the new device form?~~ Nevermind, looks to be from the form

Yes, it was through web UI.

> Version of Postgres you're running?

It's using the Omnibus packaged one:

```
firezone=# SELECT version();
                                                version
-------------------------------------------------------------------------------------------------------
 PostgreSQL 13.5 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
(1 row)
```

> can you please share your IP configs?

From one of the hosts with the problem:

```ruby
default['firezone']['wireguard']['ipv4']['enabled'] = true
default['firezone']['wireguard']['ipv4']['masquerade'] = false
default['firezone']['wireguard']['ipv4']['network'] = '10.199.0.0/21'
default['firezone']['wireguard']['ipv4']['address'] = '10.199.0.1'
```

The ones with IPv6 enabled all have a /64 assigned just for Wireguard, eg.

```ruby
default['firezone']['wireguard']['ipv6']['enabled'] = true
default['firezone']['wireguard']['ipv6']['masquerade'] = false
default['firezone']['wireguard']['ipv6']['network'] = '2400:8901:e001:91::/64'
default['firezone']['wireguard']['ipv6']['address'] = '2400:8901:e001:91::1'
```

> is IPv6 enabled

I have 6 servers, 4 of them with IPv6 enabled (and in use with Firezone) and 2 of them with only IPv4. The same problem is present across them all.

They have been updated at the same time and the configs are the same (managed by Ansible) so I am not so surprised I run into the same issue for multiple servers though.

> how many devices do you have already?

From 3 devices on one server to 12 devices on another.

**Comment by AndrewDryga** [comment] 2023-01-19 18:36
@gbe so the problem is that Firezone doesn't support /64 ranges anymore and for a good reason: your IPv4 configuration allows around 4m devices while your IPv6 allows 18446744073709551616 devices, the actual limit will be bound by the least one (IPv4 = 4m).

I pushed a fix to soft-limit that to `/70`, but you can unlock your installation right now if you just replace `/64` with `/70` or above, or better go with `/106` to match your IPv4 range.

**Closed as completed** 2023-01-20 01:16 UTC
