### ISSUE TITLE
crash on start after upgrade to 0.7.0, same issue

### ISSUE THREAD

**Issue by jahlib** [CloudFire-LLC/cloudfire#1297] opened 2023-01-13 15:51 UTC
firezone/embedded/service/firezone
  * execute[setcap_beam] action run
    - execute setcap 'cap_net_admin+eip' /opt/firezone/embedded/service/firezone/erts-13.1/bin/beam.smp
  * file[environment-variables] action create (up to date)
  * execute[database schema] action run
    
    ================================================================================
    Error executing action `run` on resource 'execute[database schema]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of bin/firezone eval "FzHttp.Release.migrate" ----
    STDOUT: 15:49:42.631 [info] == Running 20221223190406 FzHttp.Repo.Migrations.MigratePksToUuid.change/0 forward
    15:49:42.637 [info] alter table connectivity_checks
    STDERR: ** (Postgrex.Error) ERROR 23502 (not_null_violation) column "id" of relation "connectivity_checks" contains null values
    
        table: connectivity_checks
        column: id
        (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
        (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
        (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:326: Ecto.Migration.Runner.log_and_execute_ddl/3
        (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
        (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
        nofile:1: (file)
    ---- End output of bin/firezone eval "FzHttp.Release.migrate" ----
    Ran bin/firezone eval "FzHttp.Release.migrate" returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/opt/firezone/cache/cache/cookbooks/firezone/recipes/app.rb
    
     59: execute 'database schema' do
     60:   command 'bin/firezone eval "FzHttp.Release.migrate"'
     61:   cwd node['firezone']['app_directory']
     62:   environment(Firezone::Config.app_env(node))
     63:   user node['firezone']['user']
     64: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/opt/firezone/cache/cache/cookbooks/firezone/recipes/app.rb:59:in `from_file'
    
    execute("database schema") do
      action [:run]
      default_guard_interpreter :execute
      command "bin/firezone eval \"FzHttp.Release.migrate\""
      declared_type :execute
      cookbook_name "firezone"
      recipe_name "app"
      domain nil
      user "firezone"
      cwd "/opt/firezone/embedded/service/firezone"
      environment { secret_info_you_may_not_see_here }
      end
    
    System Info:
    ------------
    chef_version=17.10.0
    platform=ubuntu
    platform_version=20.04
    ruby=ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
    program_name=/opt/firezone/embedded/bin/chef-client
    executable=/opt/firezone/embedded/bin/chef-client
    
Recipe: firezone::phoenix
  * component_runit_service[phoenix] action restart
    * service[phoenix] action nothing (skipped due to action :nothing)
    * runit_service[phoenix] action restart (up to date)
     (up to date)

Running handlers:
[2023-01-13T15:49:43+00:00] ERROR: Running exception handlers
Running handlers complete
[2023-01-13T15:49:43+00:00] ERROR: Exception handlers complete
Infra Phase failed. 23 resources updated in 16 seconds
[2023-01-13T15:49:43+00:00] FATAL: Stacktrace dumped to /var/opt/firezone/cache/cache/chef-stacktrace.out
[2023-01-13T15:49:43+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-01-13T15:49:43+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2023-01-13T15:49:43+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-01-13T15:49:43+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[database schema] (firezone::app line 59) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of bin/firezone eval "FzHttp.Release.migrate" ----
STDOUT: 15:49:42.631 [info] == Running 20221223190406 FzHttp.Repo.Migrations.MigratePksToUuid.change/0 forward
15:49:42.637 [info] alter table connectivity_checks
STDERR: ** (Postgrex.Error) ERROR 23502 (not_null_violation) column "id" of relation "connectivity_checks" contains null values

    table: connectivity_checks
    column: id
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:326: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)
---- End output of bin/firezone eval "FzHttp.Release.migrate" ----
Ran bin/firezone eval "FzHttp.Release.migrate" returned 1

**Comment by AndrewDryga** [comment] 2023-01-13 18:17
Hey @jahlib, the blame it on me - looks like our test data did not cover the migration case you hit into, I'll push a fix for a migration.

**Comment by AndrewDryga** [comment] 2023-01-13 18:21
Closing as duplicate of #1295.

**Closed as completed by AndrewDryga** 2023-01-13 18:21 UTC
