### ISSUE TITLE
`Destination not allowed` spam on gateway after enabling the Internet resource

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6465] opened 2024-08-28 06:05 UTC
Steps to reproduce:

- Enable the Internet Gateway for a Client (1.3.0, needs to be AWS gateway which is also 1.3.0)
- See the log spam below
- This will occur for _each_ client that connects

```
2024-08-28T06:04:58.175170Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 2606:4700:4700::1111 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:58.176133Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 2606:4700:4700::1111 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:58.176548Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 2606:4700:4700::1111 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:58.176914Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 2606:4700:4700::1111 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:58.177781Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 2606:4700:4700::1111 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:58.178168Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 2606:4700:4700::1111 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:58.178724Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 2606:4700:4700::1111 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:59.559707Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 198.41.192.77 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:59.560274Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 198.41.192.77 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:59.759559Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 198.41.192.77 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:04:59.760818Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 198.41.192.77 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:05:00.166023Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 198.41.192.77 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:05:00.166443Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 198.41.192.77 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:05:00.253286Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 1.1.1.1 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:05:00.254424Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 1.1.1.1 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:05:00.258452Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 1.1.1.1 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:05:00.260252Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 1.1.1.1 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
2024-08-28T06:05:00.260759Z DEBUG firezone_tunnel::gateway: Invalid packet: Destination not allowed: 1.1.1.1 cid=4f498c14-22e4-4e16-9799-0483a30fa10c
```

**Comment by jamilbk** [comment] 2024-08-28 06:08
@conectado I think you need an `Allow access` call for `0.0.0.0/0, ::/0` for the Internet resource, right?

**Comment by AndrewDryga** [comment] 2024-08-28 16:59
This might be a duplicate of #6466

**Comment by AndrewDryga** [comment] 2024-08-28 18:14
@conectado right now portal will only send internet resource (a map `{id: ..., type: "internet"}`). Do you expect a different payload for it?

**Closed as completed** 2024-08-28 22:26 UTC
Labels: kind/bug, area/connlib, area/gateway, business_value/high
