### ISSUE TITLE
Browsers that enable DoH by default interfere with Firezone DNS interception

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6375] opened 2024-08-20 17:01 UTC
I believe web browsers on iOS will opportunistically use DoH for some lookups, even if they're DNS Resources. This might be caused by https://www.firezone.dev/kb/administer/troubleshooting#some-browsers-break-dns-routing

This is causing speed.cloudflare.com for example to fail to be routed by Firezone for a default installation of Firefox for macOS.

**Comment by jamilbk** [comment] 2024-08-21 00:40
Seems to be a Safari issue -- happening on macOS too.

**Comment by ReactorScram** [comment] 2024-08-22 22:22
I think I had to turn off DoH on Android Chrome recently too. On top of having to force quit the app because of the stale connections problem. (Which isn't our fault but is frustrating for users)

**Comment by thomaseizinger** [comment] 2024-08-22 23:02
Currently, we silently drop TCP connections to sentinel DNS servers I think. Should we maybe just respond with a TCP RST?

**Comment by jamilbk** [comment] 2024-09-25 17:40
This is still happening for Firefox and Chrome (default settings) on macOS.

I think we there might be a standards-compliant way to prevent them from using their own DNS:

https://support.mozilla.org/en-US/kb/dns-over-https?as=u&utm_source=inproduct#w_why-would-a-network-tell-firefox-not-to-use-secure-dns

**Comment by thomaseizinger** [comment] 2024-09-25 22:28
This sounds useful: https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet

**Comment by thomaseizinger** [comment] 2024-09-26 03:17
Also: https://wiki.mozilla.org/Security/DNS_Over_HTTPS/Heuristics#VPN_or_Proxy

**Comment by thomaseizinger** [comment] 2024-09-26 04:37
https://github.com/firezone/firezone/pull/6831 fixes this for Firefox at least. For Chrome, I couldn't reproduce any problems on a default install of MacOS.

**Comment by thomaseizinger** [comment] 2024-09-27 02:05
Fixed in #6831.

**Closed as completed by thomaseizinger** 2024-09-27 02:05 UTC
Labels: kind/bug, area/apple_client, kind/UX/user
