### ISSUE TITLE
Send portal telemetry to Stackdriver

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2141] opened 2023-09-25 17:39 UTC
We want to send OTEL metrics to Google Ops (ex Stackdriver). Currently, metrics are in beta for Elixir so we should test them out and wait for a stable release if they don't work from first attempt.

**Comment by jamilbk** [comment] 2024-01-08 18:33
Waiting on Elixir client for OT to implement metrics

**Comment by AndrewDryga** [comment] 2024-03-19 15:47
Dupe of #2014

**Closed as completed by AndrewDryga** 2024-03-19 15:47 UTC
Labels: area/portal, area/observability
