### ISSUE TITLE
in any way to possible limit bandwidth

### ISSUE THREAD

**Issue by FakeErrorX** [CloudFire-LLC/cloudfire#1317] opened 2023-01-16 02:58 UTC
Is there a way to put data traffic limit on my firezone server? for example a user only could transfer 50GB of data Down/Upload

**Comment by AndrewDryga** [comment] 2023-01-17 00:35
Hello @FakeErrorX, there are no bandwidth limits currently, but you can build out something for your use-case using REST API we just released.

**Comment by jamilbk** [comment] 2023-01-17 17:57
Hey @FakeErrorX -- we don't support setting bandwidth limits currently, would need to think more if/when that feature would be added. You could limit bandwidth _speed_ today by peer with the `tc` or `vnstat` command on the `wg-firezone` interface, though I doubt it's possible to limit total bandwidth using the same technique. That would require keeping a counter of aggregate transferred bytes per user for each peer on the WireGuard interface.

A few how-tos for inspiration:

- https://www.baeldung.com/linux/throttle-bandwidth
- https://serverfault.com/questions/507658/limit-incoming-and-outgoing-bandwidth-and-latency-in-linux
- https://www.techrepublic.com/article/how-to-limit-bandwidth-on-linux-to-better-test-your-applications/

**Closed as not planned by jamilbk** 2023-01-17 17:57 UTC

**Comment by jamilbk** [comment] 2023-01-17 17:58
Dupe of #326
