### ISSUE TITLE
displayed "access_denied :idp_first_flow_not_allowed" when Google App List clicked SAML APP

### ISSUE THREAD

**Issue by atstudio** [CloudFire-LLC/cloudfire#1803] opened 2023-07-19 01:43 UTC
**Describe the bug**
After integrating Firezone and Google Workspace SAML, I clicked the SAML Application which was registered at Google main.
However right after when I connected into Firezone, I got this error message right below.
`access_denied :idp_first_flow_not_allowed`

I attatched screenshot below.
Hope this issue would be solved.

**To Reproduce**
see screenshot below

**Expected behavior**
no show error message, login success.

**Screenshots / Logs**
<img width="354" alt="스크린샷 2023-07-19 오전 10 16 56" src="https://github.com/firezone/firezone/assets/9524764/6ce35b63-19d9-42a3-9787-88c2e079139d">
click "Firezone" App

<img width="552" alt="스크린샷 2023-07-19 오전 10 18 28" src="https://github.com/firezone/firezone/assets/9524764/9a6cb0bd-9fc1-4969-858c-67b4e73255d5">

Displayed `access_denied :idp_first_flow_not_allowed` message

**Platform (please complete the following information):**
 - Firezone Version: 0.7.32
 - OS: Linux
 - Distro: Amazon Linux 2
 - Kernel version: 5.10.184-175.731.amzn2.aarch64
 - Deployment method: Docker

**Additional context**

**Comment by jamilbk** [comment] 2023-07-19 18:46
Thanks for the report! Closing as a dupe of #1117

**Closed as not planned by jamilbk** 2023-07-19 18:46 UTC
Labels: kind/bug

**Comment by atstudio** [comment] 2023-07-20 16:54
@jamilbk Thanks. I hope it gets resolved quickly. 😄
