### ISSUE TITLE
Error during installation with docker : psql: error: connection to server at "127.0.0.1", port 5432 failed: Connection refused

### ISSUE THREAD

**Issue by MitryDim** [CloudFire-LLC/cloudfire#1481] opened 2023-03-01 22:48 UTC
**Describe the bug**
Error during installation with docker.

**To Reproduce**
Steps to reproduce the behavior: launch bash <(curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh) 1869f4f207a1318-0247b67287e4cd-26031951-4b9600-1869f4f207b190c

**Expected behavior**
I have error Resetting DB password...
psql: error: connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
**Screenshots / Logs**
[https://prnt.sc/KEK_H5Vg0Srn](https://prnt.sc/KEK_H5Vg0Srn)
[https://prnt.sc/aaXML5dDO3Z1](https://prnt.sc/aaXML5dDO3Z1)

**Platform (please complete the following information):**
 - Firezone VersionLastest 0.7.18
 - OS: Debian 
 - Distro: Debian 11
 - Kernel version: Linux version 5.10.0-21-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.162-1 (2023-01-21)
 - Deployment method: Docker

**Additional context**
If stop all docker image and puge ll and restart the installation the error is deleted and i have access to firezone but when i click on ADD device i have message Internal server error

**Comment by AndrewDryga** [comment] 2023-03-01 23:20
Duplicate of #1477. Should be fixed in the latest version (just released one).

**Closed as completed by AndrewDryga** 2023-03-01 23:20 UTC
Labels: kind/bug
