### ISSUE TITLE
How can i find the `log_directory`?

### ISSUE THREAD

**Issue by T-baby** [CloudFire-LLC/cloudfire#1632] opened 2023-05-25 11:15 UTC
I deployed the firezone using docker-compose and I was hoping to find the file with the wireguard related log output, but I didn't find it in the container.

I would like to find wireguard related logs and firezone related logs.

**Comment by jamilbk** [comment] 2023-05-26 04:04
Hi @T-baby -- Firezone doesn't interfere or intercept `wireguard` kernel logs, so whatever techniques you use for standard kernel logging (dmesg etc) would work here.

Possible dupe of https://github.com/firezone/firezone/issues/1594

**Closed as not planned by jamilbk** 2023-05-26 04:04 UTC
Labels: kind/bug
