### ISSUE TITLE
When the VPN session time is over, display a message about it and redirect all traffic to the reauthentication page

### ISSUE THREAD

**Issue by kinseii** [CloudFire-LLC/cloudfire#1493] opened 2023-03-09 07:02 UTC
**Is your feature request related to a problem? Please describe.**
If `Require Authentication For VPN Sessions` is enabled and when the VPN session is over, the traffic is simply blocked, as if the user has a problem with the Internet. There is no information that reauthentication is needed.

**Describe the solution you'd like**
When the VPN session time is over, display a message about it and redirect all traffic to the reauthentication page.

![firezone_propose1](https://user-images.githubusercontent.com/74458264/223945111-c03ff373-bf83-49e6-9bc6-464612f07496.png)

**Comment by jamilbk** [comment] 2023-03-09 14:20
Hi @kinseii, unfortunately this is technically impossible -- "redirect all traffic to the authentication page" is the problematic part. We can redirect HTTP traffic, but HTTPS and other protocols cannot be redirected.

Client apps will solve this problem.

Closing as a dupe of #689

**Closed as not planned by jamilbk** 2023-03-09 14:20 UTC
Labels: kind/feature
