### ISSUE TITLE
vpn session expire not work

### ISSUE THREAD

**Issue by lovesharepc** [CloudFire-LLC/cloudfire#1578] opened 2023-05-01 04:42 UTC
**Describe the bug**
vpn session expire not work

**To Reproduce**
when setting Require Authentication For VPN Sessions
wait UI VPN Connection status is change to expire 
but client still can establish vpn and send package

**Screenshots / Logs**
https://imgur.com/cvRIroQ
https://imgur.com/5DQB7XZ

**Platform (please complete the following information):**
 - Firezone Version [[0.7.26](https://github.com/firezone/firezone/tree/refs/tags/0.7.26)]
 - OS: [linux]
 - Distro: [Ubuntu 22.04]
 - Kernel version: [5.19.0-1022-gcp]
 - Deployment method: [Docker]

**Comment by jamilbk** [comment] 2023-05-01 15:19
Thanks for the report! We haven't changed anything in this area in some time -- when you say "send package", do you mean you can, for example, ping `1.1.1.1`?

I'm not able to reproduce, so if you could provide steps to repeat (or even better, a sample repository) that would be helpful.

**Comment by stevo11811** [comment] 2023-05-02 15:27
Version 0.7.27
 I am able to reproduce the same issue, new install of firezone on Ubuntu 22.04 LTS using docker install script.
Steps - Setup User, download profile.
Set to expire after 1 hour.
Waited for expiration, no change.
Disconnect, reconnect, no change.

My session is marked as "EXPIRED" yet i have full connectivity even after disconnecting and reconnecting, i force all traffic over the tunnel and verified it is being routed.

![image](https://user-images.githubusercontent.com/74738693/235712195-6e9523cc-a541-4f8d-a294-12dc9eabfc6a.png)

**Comment by jamilbk** [comment] 2023-05-02 18:48
Thanks for the added detail. Bear in mind it takes up to one minute for the changes to be reflected on the WireGuard interface.

To help us triage, if you `Disable` the user's VPN connection manually from the User's page, does that work (do the user's devices lose connectivity after one minute?)

**Comment by AndrewDryga** [comment] 2023-05-02 18:55
Hey @stevo11811, thank you for confirming the bug. Can you please run a few commands and share the output to give more context? It will help me to resolve it faster:
```
docker exec -it firezone-firezone-1 sh
bin/firezone remote
FzHttp.Config.vpn_sessions_expire?()
FzHttp.Config.fetch_config!(:vpn_session_duration)
FzHttp.Repo.all(FzHttp.Users.User) |> Enum.map(fn user -> {user.id, user.last_signed_in_at, FzHttp.Users.vpn_session_expired?(user)} end)
```

Also, please tell me how you configured `vpn_session_duration` (in settings or in environment variables?).

**Comment by AndrewDryga** [comment] 2023-05-02 18:57
Hey @stevo11811, thank you for confirming the bug. Can you please run a few commands to give a bit more context? It will help me to faster resolve it:
```
docker exec -it firezone-firezone-1 sh
bin/firezone remote
FzHttp.Config.vpn_sessions_expire?()
FzHttp.Config.fetch_config!(:vpn_session_duration)
FzHttp.Repo.all(FzHttp.Users.User) |> Enum.map(fn user -> {user.id, user.last_signed_in_at, FzHttp.Users.vpn_session_expired?(user)} end)
```

Also, please make sure your `vpn_session_duration` is set to a non-zero value either in settings or in environment variables.

**Comment by stevo11811** [comment] 2023-05-02 19:46
@AndrewDryga 

Sure thing! This is entirely a test box so we can do whatever with it.

My exact steps were

1. Fresh install ubuntu 22.04.
2. Latest version of docker from repo, not apt.
3. Install using script provided on site.
4. Login and change password.
5. Create a new device, download configuration/test.
6. Enable expiration through the web interface, waited until EXPIRED to perform additional testing.
7. reboot to see if any changes, nothing changed.

![image](https://user-images.githubusercontent.com/74738693/235769187-88d317b6-6c8c-4e76-a3df-2b11b6b18c96.png)

**Comment by lovesharepc** [comment] 2023-05-02 23:54
> do you mean you can, for example, ping 1.1.1.1?

yes any package  still can route from firezone



> test command output

```
/app # bin/firezone remote
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]

Interactive Elixir (1.14.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(firezone@127.0.0.1)1> 
nil
iex(firezone@127.0.0.1)2> FzHttp.Config.vpn_sessions_expire?()
true
iex(firezone@127.0.0.1)3> FzHttp.Config.fetch_config!(:vpn_session_duration)
3600
iex(firezone@127.0.0.1)4> FzHttp.Repo.all(FzHttp.Users.User) |> Enum.map(fn user -> {user.id, user.last_signed_in_at, FzHttp.Users.vpn_session_expired?(user)} end)
[
  {"4ac51b7b-f8cd-4c10-bbb8-aa58355b1619", ~U[2023-04-29 14:15:12.528164Z],
   true},
  {"dac69144-5219-416c-974c-45a37916ebcc", ~U[2023-05-01 04:33:14.856902Z],
   true}
]
```


> Disable the user's VPN connection manually  

can work

> vpn_session_duration in UI   

1hr

**Comment by alpacaccp** [comment] 2023-05-04 01:09
I can confirm this issue as well.

I suspected issue could be due to the first user is admin user, so I created a second user and set expire time to 1 hour. 

![Screenshot 2023-05-04 110449](https://user-images.githubusercontent.com/120345873/236084318-7952ce3f-0c4e-4d39-bd3e-130ca6caca0c.png)

The user was able to establish VPN connect and  could ping 1.1.1.1, also browsing google.com etc when it said expired. 

```elixir
iex(firezone@127.0.0.1)4> FzHttp.Config.vpn_sessions_expire?()
true
iex(firezone@127.0.0.1)5> FzHttp.Config.fetch_config!(:vpn_session_duration)
3600
iex(firezone@127.0.0.1)6> FzHttp.Repo.all(FzHttp.Users.User) |> Enum.map(fn user -> {user.id, user.last_signed_in_at, FzHttp.Users.vpn_session_expired?(user)} end)
[
  {"5ae7cdee-e1fa-4357-b361-1ae1feab29af", ~U[2023-05-03 23:26:19.431947Z],
   true},
  {"7bfdab16-2272-4eda-9d92-5ff2ea32a95a", ~U[2023-05-03 23:35:44.140434Z],
   true}
]
``` 


Manually disabled the VPN, the user was not able to ping 1.1.1.1 nor browsing any site.

![Screenshot 2023-05-04 105737](https://user-images.githubusercontent.com/120345873/236084342-46189be3-1db5-48b1-b19c-2e97e3d0487f.png)

**Closed as completed** 2023-05-04 21:17 UTC
Labels: kind/bug

**Comment by lovesharepc** [comment] 2023-05-07 07:17
verify 0.7.28 is fixed
thank for fast fix this bug
