### ISSUE TITLE
(#1498) break pod again

### ISSUE THREAD

**Issue by laweschan** [CloudFire-LLC/cloudfire#1502] opened 2023-03-11 03:33 UTC
**Describe the bug**
ip: RTNETLINK answers: File exists ERROR pop-up again during fresh deployment in Podman using Pod-containers 

**To Reproduce**
create pod container pod-firezone
create container postgres belong to pod-firezone
create container firezone belong to pod-firezone /bin/migrate
create container firezone belong to pod-firezone /create-or-reset-admin
  ERROR--> ip: RTNETLINK answers: File exists

**Expected behavior**
 using pod technology, wg-firezone interface is belong to pod-container in podman 
 if detect wg-firezone exists or not, before force create the interface in each step (/bin/migrate ---> /bin/create-or-reset-admin --> launch firezone container ), then the podman pod container can run as expect like 0.7.13 version.

   now the pod technology can't apply to firezone since the wg-interface always conflict

**Screenshots / Logs**
    ip netns exec netns-de90b8b9-2ad9-7b50-b31b-b1459ff3d1c1 ip a

   output:
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 82:44:fe:c0:ca:0d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.25.0.100/16 brd 172.25.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:3990:3990::99/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::8044:feff:fec0:ca0d/64 scope link
       valid_lft forever preferred_lft forever
3: wg-firezone: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1280 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 100.64.0.1/32 scope global wg-firezone
       valid_lft forever preferred_lft forever
    inet6 fd00::1/128 scope global
       valid_lft forever preferred_lft forever
  
     as show in above, wg-firezone is exists at namespace that belong to pod-container, --rm in firezone container will not help to remove wg-firezone, everytime the script call firezone container pod will just detect wg-firezone already exists, and show ip link exists error. 
   
**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.22]
 - OS: [Fedora]
 - Distro: [37]
 - Kernel version: [e.g. 6.1.14]
 - Deployment method: [e.g. Podman Pod container]

**Additional context**

**Comment by AndrewDryga** [comment] 2023-03-13 18:14
Duplicate of #1506

**Closed as completed by AndrewDryga** 2023-03-13 18:14 UTC
Labels: kind/bug
