### ISSUE TITLE
`Invalid packet: Unsupported ICMPv4 type: 3`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6373] opened 2024-08-20 16:41 UTC
Type 3 is a response from the router `Destination unreachable`. It's hard to say what Resource this was for since I'm routing a lot through the Gateway. Just noting down here for future.

```
2024-08-20T16:40:56.221213Z DEBUG firezone_tunnel::gateway: Invalid packet: Unsupported ICMPv4 type: 3 cid=d228d739-1a37-4f82-a096-4f450ff2684f
2024-08-20T16:40:56.221812Z DEBUG firezone_tunnel::gateway: Invalid packet: Unsupported ICMPv4 type: 3 cid=d228d739-1a37-4f82-a096-4f450ff2684f
```

**Comment by jamilbk** [comment] 2024-08-20 16:46
Also seeing the ICMPv6 equivalent:

```
2024-08-20T16:45:14.453473Z DEBUG firezone_tunnel::gateway: Failed to encapsulate: Unsupported ICMPv6 type: 1 cid=d228d739-1a37-4f82-a096-4f450ff2684f
```

**Comment by thomaseizinger** [comment] 2024-08-20 21:30
Dupe of https://github.com/firezone/firezone/issues/5614.

**Closed as not planned** 2024-08-20 21:43 UTC
Labels: kind/feature, area/connlib, kind/UX/user
