### ISSUE TITLE
Default admin credentials don't work

### ISSUE THREAD

**Issue by ethindp** [CloudFire-LLC/cloudfire#2066] opened 2023-09-13 18:12 UTC
**Describe the bug**
I've just set up firezone through the mash Ansible playbook, but I can't log in with the default credentials I set up, even though I reset them twice via create-or-reset-admin.

**To Reproduce**

Follow the steps for [setting up Firezone](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/services/firezone.md) and try to log in with the default credentials you configured.

**Expected behavior**
I should be able to login.

**Screenshots / Logs**

**Platform (please complete the following information):**
 - Firezone Version: 0.7.30-0
 - OS: Linux
 - Distro: Arch Linux
 - Kernel version: 6.4.14-hardened1-1-hardened
 - Deployment method: Docker

**Additional context**

**Comment by jamilbk** [comment] 2023-09-22 21:51
Please make sure you're using a password that's at least 12 characters long and that the password is _actually_ being reset (you should see logs in the `postgres` container output related to it).

**Comment by jamilbk** [comment] 2023-09-22 21:52
Closing as not able to reproduce.

**Closed as not planned by jamilbk** 2023-09-22 21:52 UTC
Labels: needs triage
