### ISSUE TITLE
Improve options related to OIDC "Auto disable VPN"

### ISSUE THREAD

**Issue by lucasbaile** [CloudFire-LLC/cloudfire#1431] opened 2023-02-15 11:16 UTC
**Is your feature request related to a problem? Please describe.**
The issue I'm facing currently is that I've got a google OIDC connection configured on my Firezone VPN, and everything is working fine, but I wanted to use the "Auto disable VPN" option, as it looks very handy in case we forget to manually remove a user that was already removed from our company gsuite. 

But apparently we're getting OIDC refresh errors every once in a while for some users, and thus they are having the connection disabled. The problem is that those are valid working users, and it seems is just a temporary connectivity issue. If I proceed to manually refresh the OIDC status on this user, the "Refresh Result" does go back to "OK", but it stays disabled

**Describe the solution you'd like**
From what I can tell, it seems there is no retry logic on this OIDC refresh error, because I noticed some users were disabled for multiple days. So I believe this feature is very handy but a bit flawed, and it could be improved with a retry logic that periodically retries to refresh the OIDC status of the user and then re-enables its connection. Maybe that retry logic could also be an option, in case there is any use case that doesn't want it. But I do think with the false-negative errors I'm facing its not viable for use for us.

**Describe alternatives you've considered**
For now my alternative is to disable this and rely on manually removing the users, which is not a big deal, but I do think that option can be very useful with minor tweaks!

**Comment by AndrewDryga** [comment] 2023-02-16 00:55
Hello @lucasbaile, we are actually thinking to remove that feature because it's very ambiguous, and to have SCIM implemented some time in the future to replace it, which will de-provision users right away after you remove them from your auth provider.

**Comment by lucasbaile** [comment] 2023-02-16 16:55
> Hello @lucasbaile, we are actually thinking to remove that feature because it's very ambiguous, and to have SCIM implemented some time in the future to replace it, which will de-provision users right away after you remove them from your auth provider.

I see, thanks for explanation! 

In that case should I just close this?

**Comment by AndrewDryga** [comment] 2023-02-16 17:01
I will close it, thank you for understanding, I know it's not the answer you were looking for.

**Closed as completed by AndrewDryga** 2023-02-16 17:01 UTC
Labels: kind/feature

**Comment by AndrewDryga** [comment] 2023-02-16 17:02
Duplicate of #1437
