### ISSUE TITLE
`Invalid dest address` during normal operation

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5605] opened 2024-06-27 17:58 UTC
@conectado thinks it will happen when traffic is seen for a DNS Resource that has not been queried by the peer yet. This peer is my Client `2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b`.

No deploys were running, no connection roaming. Just 1.1.0 macOS client.

```
Jun 27 17:45:27 perf sudo[1697696]: 2024-06-27T17:45:27.694902Z  WARN firezone_tunnel::peer: unallowed packet dst=100.96.1.180
Jun 27 17:45:27 perf sudo[1697696]: 2024-06-27T17:45:27.695213Z  WARN firezone_tunnel::gateway: Invalid packet: Invalid dest address conn_id=4f498c14-22e4-4e16-9799-0483a30fa10c local=[2001:19f0:5401:14df::]:35317 from=[2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b]:61574
Jun 27 17:45:27 perf sudo[1697696]: 2024-06-27T17:45:27.695353Z  WARN firezone_tunnel::peer: unallowed packet dst=100.96.1.180
Jun 27 17:45:27 perf sudo[1697696]: 2024-06-27T17:45:27.695505Z  WARN firezone_tunnel::gateway: Invalid packet: Invalid dest address conn_id=4f498c14-22e4-4e16-9799-0483a30fa10c local=[2001:19f0:5401:14df::]:35317 from=[2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b]:61574
Jun 27 17:45:27 perf sudo[1697696]: 2024-06-27T17:45:27.695898Z  WARN firezone_tunnel::peer: unallowed packet dst=100.96.1.180
Jun 27 17:45:27 perf sudo[1697696]: 2024-06-27T17:45:27.696025Z  WARN firezone_tunnel::gateway: Invalid packet: Invalid dest address conn_id=4f498c14-22e4-4e16-9799-0483a30fa10c local=[2001:19f0:5401:14df::]:35317 from=[2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b]:61574
Jun 27 17:45:27 perf sudo[1697696]: 2024-06-27T17:45:27.721342Z  INFO firezone_tunnel::gateway: Allowing access to resource client=4f498c14-22e4-4e16-9799-0483a30fa10c resource=656bf11c-d090-436e-b8c8-9a53aac1c024 expires=Some("2024-07-04T10:03:09+00:00")
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.745662Z  WARN firezone_tunnel::peer: unallowed packet dst=100.96.2.28
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.746325Z  WARN firezone_tunnel::gateway: Invalid packet: Invalid dest address conn_id=4f498c14-22e4-4e16-9799-0483a30fa10c local=[2001:19f0:5401:14df::]:35317 from=[2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b]:61574
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.749108Z  WARN firezone_tunnel::peer: unallowed packet dst=100.96.2.28
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.749275Z  WARN firezone_tunnel::gateway: Invalid packet: Invalid dest address conn_id=4f498c14-22e4-4e16-9799-0483a30fa10c local=[2001:19f0:5401:14df::]:35317 from=[2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b]:61574
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.749464Z  WARN firezone_tunnel::peer: unallowed packet dst=100.96.2.28
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.749533Z  WARN firezone_tunnel::gateway: Invalid packet: Invalid dest address conn_id=4f498c14-22e4-4e16-9799-0483a30fa10c local=[2001:19f0:5401:14df::]:35317 from=[2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b]:61574
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.749757Z  WARN firezone_tunnel::peer: unallowed packet dst=100.96.2.28
Jun 27 17:45:41 perf sudo[1697696]: 2024-06-27T17:45:41.749854Z  WARN firezone_tunnel::gateway: Invalid packet: Invalid dest address conn_id=4f498c14-22e4-4e16-9799-0483a30fa10c local=[2001:19f0:5401:14df::]:35317 from=[2600:1700:3ecb:2410:5cb9:9bc2:327d:f9b]:61574
```

**Comment by conectado** [comment] 2024-06-28 00:23
To add to this issue, the problem is that the flow of packets might start before the Gateway resolves the IP.

This could be either because the gateway is resolving it or the allowed message hasn't arrived yet but we already have a connection.

For the former that will probably be improved as part #5542, adding them as allowed even before resolving them and having a cache that will make resolution faster.

The latter there's not much we can do, so we will lower the log level.

**Comment by thomaseizinger** [comment] 2024-06-28 01:11
> The latter there's not much we can do, so we will lower the log level.

Already happening in https://github.com/firezone/firezone/pull/5612.

**Comment by thomaseizinger** [comment] 2024-06-30 07:15
Once we have a control protocol between client and gateway, we could send [DNS update](https://datatracker.ietf.org/doc/html/rfc2136) messages to the gateway directly, informing it about the newly assigned IPs.

We could already do that when we mint the new IPs, i.e. when they are first queried. If we send a DNS update message to every connected gateway, the mapping should definitely be established before we send the first packets to it.

**Comment by thomaseizinger** [comment] 2024-08-20 07:24
I don't think there is much we can do about these race conditions. I'd rather opportunistically send the packets to the gateway, in case the `allow_access` call is fast enough than to synchronise this.

Feel free to re-open if you disagree.

**Closed as not planned by thomaseizinger** 2024-08-20 07:24 UTC
Labels: kind/bug, area/connlib, area/gateway
