### ISSUE TITLE
Re-establish DNS mapping in client when packet from existing mapping is seen and not connected to existing peer

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3369] opened 2024-01-23 23:08 UTC
When we resolve an IP for SplitDNS, we create a peer mapping that contains the resolved IP.

If the Gateway goes down or is rebooted, that mapping goes stale and we never detect `resource_intent`s to that mapped IP again, so the packets to dummy IP get dropped because they're not connected to any peer.

This can be mitigated by the application re-resolving the IP again, but it would be nice for this mapping to be gracefully re-established.

**Comment by jamilbk** [comment] 2024-02-14 19:34
This won't work because we have only Layer 3 information to identify the source traffic for reversing the external IP back into the proxied IP to send data back to the downstream application.

**Comment by jamilbk** [comment] 2024-04-04 22:26
I think this also happens when the portal and/or relay is restarted while the mapping is in place? Is that possible?

**Comment by jamilbk** [comment] 2024-04-05 22:06
I think this is what's causing #4521 -- if DNS mappings fail to be refreshed before TURN credentials expire that would explain this behavior

**Comment by jamilbk** [comment] 2024-04-08 18:16
100.64.0.1 -> 10.10.10.10 <site-a> -> gitlab.company.com
100.64.0.1 -> 10.10.10.10 <site-a> -> jira.company.com
100.64.0.2 -> 10.10.10.10 <site-b -> foo.company.com

100.64.0.1 -> <site-a> -> new gateway: resolve (gitlab.company.com, jira.company.com): new_mappings (10.10.10.10)



First priority:
- Don't drop connections on redeploy
- Don't invalidate credentials redeploy

**Comment by conectado** [comment] 2024-04-09 01:09
> I think this is what's causing #4521 -- if DNS mappings fail to be refreshed before TURN credentials expire that would explain this behavior

With#4548 we can fix this, though I'm not sure that this is the cause behind this.

For 

> 100.64.0.1 -> 10.10.10.10 -> gitlab.company.com 100.64.0.1 -> 10.10.10.10 -> jira.company.com 100.64.0.2 -> 10.10.10.10 <site-b -> foo.company.com
> 
> 100.64.0.1 -> -> new gateway: resolve (gitlab.company.com, jira.company.com): new_mappings (10.10.10.10)
> 
> First priority:
> 
>     * Don't drop connections on redeploy
> 
>     * Don't invalidate credentials redeploy

The original idea was

* When we see a packet for an IP which is a DNS resource that doesn't have a peer we check if we ever resolved a corresponding mapping
* If we did we try to connect to a gateway in the same site or reuse the connection on that one, and send all resources that queried to that external ip along with the ip
* When the gateway sees these message it works as a normal allow_acces or reuse_connection message but instead of resolving the ip it does a reverse query for the IP and accept its depending if this is consistent with the sent ip/name pairs
* if there's some inconsistency we simply keep dropping packets otherwise connections will be resumed even if there is no new DNS query

The problem with this approach is that the reverse-lookup are not very consistent.

If we simply lookup a record and compare we run the risk of some servers doing round-robin or other dns load-balancing method preventing this from working (google wouldn't for example)

If we actually did a reverse lookup using PTR records most of the time there is a single record present preventing this from listing all possible domain names.

I'm not sure if there's a reliable way to do a reverse lookup, I'm open to ideas here

**Comment by jamilbk** [comment] 2024-04-09 01:40
@conectado Yeah I think we can maybe save this issue for the explicit case for handling Gateway restarts, which will kill the application-layer connection anyway, so DNS will be re-queried.

I think with the fix coming in #4548 that will solve the common case of keeping connections alive during deploys, so maybe refreshing mappings based on packet intents won't ever be needed.

**Comment by conectado** [comment] 2024-04-09 01:54
> @conectado Yeah I think we can maybe save this issue for the explicit case for handling Gateway restarts, which will kill the application-layer connection anyway, so DNS will be re-queried.

Not neccesarily, if an application such as a browser caches the DNS queries then it wouldn't re-query the DNS

**Comment by jamilbk** [comment] 2024-04-09 02:01
> Not neccesarily, if an application such as a browser caches the DNS queries then it wouldn't re-query the DNS

Yeah, we may just need to communicate this to admins and do some more investigation on what exactly will invalidate the browser DNS cache.

**Comment by thomaseizinger** [comment] 2024-06-25 06:13
Irrelevant after #4994.

**Closed as not planned by thomaseizinger** 2024-06-25 06:13 UTC
Labels: area/connlib
