### ISSUE TITLE
Properly handle dual-stack Relays with the same DB ID

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4726] opened 2024-04-20 23:23 UTC
At a coffee with no IPv6 connectivity, but snownet keeps trying to connect to IPv6 relays:

```
connlib	16:20:13.933105-0700	sendmsg error: Os { code: 65, kind: HostUnreachable, message: "No route to host" }, Transmit: { destination: [2600:1900:40c0:3149:0:58::]:3478, src_ip: None, enc: None, len: 152, segment_size: None }
connlib	16:20:14.077511-0700	Updated lifetime of allocation  lifetime=Lifetime(600s) relay_ip4=Some(Candidate(relay=34.89.59.190:55845/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:40c0:3149:0:58::]:55845/udp prio=50331647)) srflx=Some(Candidate(srflx=107.197.104.130:51517/udp base=192.168.1.249:51517 prio=1694498559))
connlib	16:20:14.079274-0700	Failed to decapsulate incoming packet: Packet was not accepted by any wireguard tunnel; num_tunnels = 0  from=35.227.29.149:3478 local=192.168.1.249:51517 num_bytes=48
connlib	16:20:14.116368-0700	Signalling protocol completed  duration_since_intent=275.08875ms remote=486234e1af1a696194ecdcacdfa2c8894c8b0c0ffad40feded6574a0746f636b
connlib	16:20:14.125462-0700	Already got a channel
connlib	16:20:14.125704-0700	Already got a channel
connlib	16:20:14.125926-0700	Allocation is suspended
connlib	16:20:14.126076-0700	Already got a channel
connlib	16:20:14.126214-0700	Allocation is suspended
connlib	16:20:14.126349-0700	Already binding a channel to peer
connlib	16:20:14.126487-0700	Allocation is suspended
connlib	16:20:14.126745-0700	Already got a channel
connlib	16:20:14.126883-0700	Already got a channel
connlib	16:20:14.127019-0700	Allocation is suspended
connlib	16:20:14.127161-0700	Already got a channel
connlib	16:20:14.127300-0700	Allocation is suspended
connlib	16:20:14.127465-0700	Already binding a channel to peer
connlib	16:20:14.127664-0700	Allocation is suspended
connlib	16:20:14.128810-0700	Already got a channel
connlib	16:20:14.129008-0700	Already got a channel
connlib	16:20:14.129152-0700	Allocation is suspended
connlib	16:20:14.129285-0700	Already got a channel
connlib	16:20:14.129416-0700	Allocation is suspended
connlib	16:20:14.129590-0700	Already binding a channel to peer
connlib	16:20:14.129734-0700	Allocation is suspended
connlib	16:20:14.130043-0700	Already got a channel
connlib	16:20:14.130209-0700	Already got a channel
connlib	16:20:14.130414-0700	Allocation is suspended
connlib	16:20:14.130635-0700	Already got a channel
connlib	16:20:14.130774-0700	Allocation is suspended
connlib	16:20:14.130902-0700	Already binding a channel to peer
connlib	16:20:14.131175-0700	Allocation is suspended
connlib	16:20:14.131421-0700	Already got a channel
connlib	16:20:14.131551-0700	Already got a channel
connlib	16:20:14.131719-0700	Allocation is suspended
connlib	16:20:14.131848-0700	Already got a channel
connlib	16:20:14.131949-0700	Allocation is suspended
connlib	16:20:14.132150-0700	Already binding a channel to peer
connlib	16:20:14.132333-0700	Allocation is suspended
connlib	16:20:14.132581-0700	Already got a channel
connlib	16:20:14.132710-0700	Already got a channel
connlib	16:20:14.132852-0700	Allocation is suspended
connlib	16:20:14.133064-0700	Already got a channel
connlib	16:20:14.133193-0700	Allocation is suspended
connlib	16:20:14.133290-0700	Already binding a channel to peer
connlib	16:20:14.133387-0700	Allocation is suspended
connlib	16:20:14.133763-0700	Already got a channel
connlib	16:20:14.133877-0700	Already got a channel
connlib	16:20:14.134079-0700	Allocation is suspended
connlib	16:20:14.134181-0700	Already got a channel
connlib	16:20:14.134321-0700	Allocation is suspended
connlib	16:20:14.134515-0700	Already binding a channel to peer
connlib	16:20:14.134793-0700	Allocation is suspended
connlib	16:20:14.135740-0700	Already got a channel
connlib	16:20:14.136539-0700	Already got a channel
connlib	16:20:14.136873-0700	Already got a channel
connlib	16:20:14.137058-0700	Already got a channel
```

This does not recover, it causes a loop of ICE timeouts, creating a flaky connection to resources.

**Comment by jamilbk** [comment] 2024-04-20 23:26
Full logs from the client. Can get Gateway logs if needed, but 99% sure this is a client issue: this seems to only happen from networks where I have no IPv6 connectivity.

Note that I _did_ have an active IPv6 address, then closed my laptop, went to a coffee shop with no IPv6 address, and it started acting up. Firezone was signed in the entire time. I noticed that the DNS mapping keeps failing -- every time I try to ping `github.com` I get a new mapping.

[connlib.2024-04-20-08-16-52.log.zip](https://github.com/firezone/firezone/files/15050094/connlib.2024-04-20-08-16-52.log.zip)

**Comment by jamilbk** [comment] 2024-04-20 23:29
> Failed to decapsulate incoming packet: Packet was not accepted by any wireguard tunnel; num_tunnels = 0  from=35.227.29.149:3478 local=192.168.1.249:51517 num_bytes=48

This is a really weird message. 

Ok I found an issue -- the coffee shop assigned me an IPv4 LAN address that conflicts with a Resource 😆. What to do in these cases...

**Comment by thomaseizinger** [comment] 2024-04-22 07:02
I think the cause of this is that as part of https://github.com/firezone/firezone/pull/4567, we started indexing relays by ID. In the `init` message we are given 4 relays. But two of them have the same ID because the IPv4 and IPv6 address are returned as separate entries.

That means we currently overwrite either the IPv4 `Allocation` with the IPv6 one or vice versa. So if you first ended up using a relay over IPv6 and later you suddenly no longer have an IPv6 socket, we are kind of screwed.

A quick fix for this is to return different IDs for these different addresses but the proper fix is figuring out how to model this in the client.

**Comment by thomaseizinger** [comment] 2024-04-22 07:08
Some initial thoughts:

- A relay can be reachable on either IPv4, IPv6 or both.
- A client / gateway can either have an IPv4, IPv6 socket or both.
- `reconnect` must reset whatever state we determined we are in.
- If a relay is in dual-stack mode and the client is too, we need a deterministic decision on whether to use IPv4 or IPv6.

**Comment by thomaseizinger** [comment] 2024-04-22 07:12
What has been bothering me for a while with our `Allocation` is that we don't do STUN separately but we do it as part of `ALLOCATE`. That however requires valid credentials which means the first request will always fail (because we don't have a nonce yet).

If we make an `Allocation` aware of the two IPs that the relay is listening on, figuring out which one to use is a bit of an issue. If we just send an `ALLOCATE` to both, then we might create redundant state (remember that from TURN's perspective, a client is always indexed by its 3-tuple and thus different IP means different client).

So starting with an `ALLOCATE` request might be the wrong approach. We could start with a `BINDING` request (i.e. plain STUN) for each IP and see what we get back. If we receive a response for both, we deterministically pick one of the two. If we only receive a response for one (plus some timeout), we "disable" the other IP and make an allocation using the one that worked.

**Comment by jamilbk** [comment] 2024-04-22 15:07
> So starting with an ALLOCATE request might be the wrong approach. We could start with a BINDING request (i.e. plain STUN) for each IP and see what we get back. If we receive a response for both, we deterministically pick one of the two. If we only receive a response for one (plus some timeout), we "disable" the other IP and make an allocation using the one that worked.

Just so I'm following, this is what happens on the `reconnect` right? I.e. interface properties change.

If you receive a response for both I would go for picking IPv4 -- will probably have a lower chance of being misconfigured and more available. Assuming this process is repeated during a `reconnect` of course in case WiFi network is changed or something.

**Comment by jamilbk** [comment] 2024-04-22 15:28
@thomaseizinger If TURN treats them as different Relays altogether, I wonder if we should just do the same in connlib. A fix for this would be to simply append `-4` or `-6` to the ID when returned from the Portal, or to append something similar before indexing for lookups in `connlib`. Probably the latter makes more sense.

This issue would just be concerned with fixing the bug so we can ship this ASAP and then the Allocation logic cleanup can happen in the next release -- wdyt @thomaseizinger ?

**Comment by thomaseizinger** [comment] 2024-04-22 21:30
> This issue would just be concerned with fixing the bug so we can ship this ASAP and then the Allocation logic cleanup can happen in the next release -- wdyt @thomaseizinger ?

I am pretty confident that I can properly fix this today. If we wanted to quick-fix this, then I think doing so in the portal would be better because it would automatically apply to all clients without making a new release.

It is important that it stays a valid UUID though because we currently parse it as such. That is unnecessarily restrictive so I'll fix that too.

**Comment by jamilbk** [comment] 2024-04-22 23:03
> I am pretty confident that I can properly fix this today.

SGTM will be around for any questions etc. Portal quick-fix seems more like a hack as you noted, since we would either need to generate different Relay records for the same physical Relay or use dummy DB IDs.

**Comment by thomaseizinger** [comment] 2024-04-23 01:48
@AndrewDryga I think this might be a good opportunity to tidy up the JSON structures we have for relays.

Currently, the structure for a TURN server is the following:

```json
{
    "id": "6a7f3ba9-d9c4-4633-81ab-311276993fbd",
    "expires_at": 1686629954,
    "password": "OXXRDJ7lJN1cm+4+2BWgL87CxDrvpVrn5j3fnJHye98",
    "type": "turn",
    "addr": "189.172.73.111:3478",
    "username":"1686629954:C7I74wXYFdFugMYM"
}
```

- We are effectively no longer using `type: stun`
- We now need both addresses of a relay in one object

I'll work around this for now on the client because it needs to be backwards-compatible anyway. My suggestion would be to add a new fields `relays_v2` that has the following structure:

```json
[
	{
	    "id": "6a7f3ba9-d9c4-4633-81ab-311276993fbd",
	    "expires_at": 1686629954,
	    "password": "OXXRDJ7lJN1cm+4+2BWgL87CxDrvpVrn5j3fnJHye98",
	    "addr_v4": "...",
	    "addr_v6": "...",
	    "username":"1686629954:C7I74wXYFdFugMYM"
	}
]
```

Both, `addr_v4` and `addr_v6` can be null (although at least one should be set).

My reasoning for a new field is:

- I already ignore everything with `type: stun` in `relays_presence` and `init`
- Parsing a new field is backwards-compatible because it is ignored by older clients

**Closed as completed** 2024-04-24 03:59 UTC
Labels: kind/bug, area/connlib, kind/UX/admin
