### ISSUE TITLE
Renew VPN sessions while using Keycloak 

### ISSUE THREAD

**Issue by emferrandi** [CloudFire-LLC/cloudfire#1524] opened 2023-03-22 08:11 UTC
**Describe the bug**
I'm using Keycloak and Firezone together to provide a VPN with MFA.
When I create a device on Firezone, all works very well. When I'm using VPN session, it's a bit more complicated.
Let's explain, I'm logging in on Firezone, the reauthentication devices don't work, the VPN blocks all traffic.

Moreover, I also tried without Keycloak configured on Firezone and the first connection doesn't renew VPN session. I'm forced to use the url "Reauthenticate" on the user page. 

**To Reproduce**
Two environments configured like these : 
Firezone : 
-  Require Authentication For VPN Sessions : Every hours 
- OIDC Configuration :
  - Scope : "openid email profile"
  - Discovery Document URI : http://keycloak.test.com/auth/realms/RealmVPNFirezone/.well-known/openid-configuration
  - https://firezone.test.com/auth/oidc/firezone/callback/
  -  Auto-create users : True

Keycloak : 
- Client > Client Protocol : openid-connect 
- Client > Direct Access Grant Enabled : ON
- Client > Valid Redirect URI : https://firezone.test.com/auth/oidc/firezone/callback/ & https://firezone.test.com/
- Client > Proof Key for Code Exchange Code Challenge Method : S256
- Authentication > Flows > Forms > Browser - Conditional OTP : Required 
- Authentication > OTP Policy : FreeOTP

**Expected behavior**
When I connect to Firezone, I want the VPN session to be renewed again from the first authentication.

**Screenshots / Logs**
No log regarding my issue.

**Platform (please complete the following information):**
 - Firezone Version : 0.7.25
 - OS: Debian 
 - Distro: bullseye
 - Kernel version: 5.10.0-21-amd64
 - Deployment method: Docker

**Comment by jamilbk** [comment] 2023-05-23 00:22
@emferrandi Thanks for the report. We're shipping a revamped OIDC layer and user provisioning architecture for 1.0 and this should be addressed by that. Closing for now.

**Closed as not planned by jamilbk** 2023-05-23 00:22 UTC
Labels: kind/feature

**Comment by jamilbk** [comment] 2023-06-21 23:56
Hi @emferrandi,

Unfortunately we're unable to reproduce the issue. Is the user _actually_ being reauthenticated via Keycloak, or just passed through?

You may want to make sure the Keycloak authentication session for Firezone is shorter than the `vpn_session_duration` -- otherwise the user won't actually be reauthenticated, which would cause this issue.
