### ISSUE TITLE
Group Push when Okta is used as IdP

### ISSUE THREAD

**Issue by gvecchicert** [CloudFire-LLC/cloudfire#1695] opened 2023-06-26 14:31 UTC
**Is your feature request related to a problem? Please describe.**
Per-user Egress rules and admin role do not scale.

**Describe the solution you'd like**
Allow configure Egress rules and admin role per-group basis, groups will be pushed by Okta.

**Describe alternatives you've considered**
Copy and paste :(

**Additional context**
Group Push is a must-have for every size Company using Okta.

**Comment by jamilbk** [comment] 2023-06-28 01:47
Hi @gvecchicert -- are you referring specifically to SCIM 2.0 support, like in #1437?

**Comment by gvecchicert** [comment] 2023-06-28 07:59
Hi @jamilbk 

I'm not a SCIM master, but I'm looking a way to manage Egress rules and Admin role per group (not per user as currently allowed) and groups are pushed by Okta with [Group Push](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-about-group-push.htm).

**Comment by jamilbk** [comment] 2023-06-28 14:37
Understandable! In that case I'm going to close this as a dupe of #1157

This will be coming in 1.0, ETA Q3. Happy to include you as a beta tester if you'd like. Fill [this out](firezone.dev/contact/sales) or just shoot me an email (jamil firezone dev)

**Closed as not planned by jamilbk** 2023-06-28 14:37 UTC
Labels: kind/feature
